export const MAX_GROUP_NAME_LENGTH = 30;
export const MAX_PARTICIPANT_NAME_LENGTH = 20;

export const MAX_PARTICIPANTS_PER_GROUP = 100;
export const MAX_DATE_RANGE_DAYS = 180;
export const MAX_AVAILABLE_DAYS_PER_PARTICIPANT = 365;
export const MAX_POLL_CANDIDATES = 10;
export const MAX_VOTES_PER_PARTICIPANT = 10;
export const MAX_DESCRIPTION_LENGTH = 1000;
export const MAX_EMAIL_LENGTH = 255;
